{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecret.secretName }}
  namespace: {{ include "chart.namespace" . }}
  labels:
    app.kubernetes.io/component: secret
    {{- include "chart.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreRef.name }}
    kind: {{ .Values.externalSecret.secretStoreRef.kind }}
  target:
    name: {{ .Values.externalSecret.secretName }}
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      metadata:
        labels:
          app.kubernetes.io/component: secret
          {{- include "chart.labels" . | nindent 10 }}
      data:
        KEYCLOAK_CLIENT_SECRET: '{{`{{ .KEYCLOAK_CLIENT_SECRET }}`}}'
  data:
    - secretKey: KEYCLOAK_CLIENT_SECRET
      remoteRef:
        key: {{ .Values.externalSecret.vaultPath }}
        property: KEYCLOAK_CLIENT_SECRET
{{- end }}
