{{- if .Values.imagePullSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.imagePullSecret.name }}
  namespace: {{ include "chart.namespace" . }}
  labels:
    app.kubernetes.io/component: image-pull-secret
    {{- include "chart.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreRef.name }}
    kind: {{ .Values.externalSecret.secretStoreRef.kind }}
  target:
    name: {{ .Values.imagePullSecret.name }}
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: kubernetes.io/dockerconfigjson
      metadata:
        labels:
          {{- include "chart.labels" . | nindent 10 }}
  data:
    - secretKey: .dockerconfigjson
      remoteRef:
        key: {{ .Values.imagePullSecret.vaultPath }}
        property: {{ .Values.imagePullSecret.vaultKey }}
{{- end }}
