apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}
  namespace: {{ include "chart.namespace" . }}
  labels:
    app.kubernetes.io/component: mcp-server
    {{- include "chart.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}
