apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: regcred-maps-mcp-server
  namespace: teams
spec:
  data:
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: jquad/production/harbor
      metadataPolicy: None
      property: DOCKERCONFIGJSON
    secretKey: .dockerconfigjson
  refreshInterval: 1h0m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-cluster-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: regcred-maps-mcp-server
    template:
      type: kubernetes.io/dockerconfigjson
      metadata:
        labels:
          environment: teams
