apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: teams

resources:
- namespace.yaml
- configmap.yaml
- secret.yaml
- deployment.yaml
- valhalla.yaml
- nominatim.yaml

images:
- name: maps-mcp-server
  newName: maps-mcp-server
  newTag: latest
